import { createContext, useContext, useEffect, useState } from "react";

type Language = "en" | "th";

type LanguageProviderProps = {
  children: React.ReactNode;
  defaultLanguage?: Language;
};

type LanguageProviderState = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const LanguageProviderContext = createContext<
  LanguageProviderState | undefined
>(undefined);

// Simple translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.title": "Ban Phuttachad Dormitory",
    "nav.dashboard": "Dashboard",
    "nav.rooms": "Rooms",
    "nav.tenants": "Tenants",
    "nav.staff": "Staff",
    "nav.billing": "Billing",
    "nav.repairs": "Repairs",
    "nav.announcements": "Announcements",
    "nav.reports": "Reports",
    "nav.profile": "Profile",
    "nav.settings": "Settings",
    "auth.login": "Login",
    "auth.logout": "Logout",
    "auth.register": "Register",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.role": "Role",
    "auth.welcomeBack": "Welcome back",
    "auth.pleaseLogin": "Please login to continue",
    "dashboard.welcome": "Welcome to your Dashboard",
    "dashboard.summary": "Here's a summary of your dormitory",
    "dashboard.totalRooms": "Total Rooms",
    "dashboard.occupiedRooms": "Occupied",
    "dashboard.vacantRooms": "Vacant",
    "dashboard.pendingRepairs": "Pending Repairs",
    "dashboard.monthlyRevenue": "Monthly Revenue",
    "dashboard.Description": "Revenue trend over the last 6 months",
    "rooms.management": "Room Management",
    "rooms.number": "Room Number",
    "rooms.type": "Room Type",
    "rooms.status": "Status",
    "rooms.rent": "Monthly Rent",
    "rooms.size": "Room Size",
    "rooms.add": "Add Room",
    "rooms.add_description": "Add a new room to the dormitory.",
    "Standard.Single": "Standard Single Room",
    "Standard.Double": "Standard Double Room",
    "satatus.occupied": "Occupied",
    "satatus.vacant": "Vacant",
    "satatus.maintenance": "Maintenance",
    "rooms.capacity": "Capacity",
    "rooms.Floor": "Floor",
    "status.text": "Room Status",
    "rooms.edit": "Edit Room",
    "rooms.delete": "Delete Room",
    "tenants.management": "Tenant Management",
    "tenants.name": "Name",
    "tenants.room": "Room",
    "tenants.contactInfo": "Contact Info",
    "tenants.leaseStart": "Lease Start",
    "tenants.leaseEnd": "Lease End",
    "tenants.add": "Add Tenant",
    "tenants.edit": "Edit Tenant",
    "tenants.delete": "Delete Tenant",
    "repairs.management": "Repair Management",
    "repairs.room": "Room",
    "repairs.description": "Description",
    "repairs.status": "Status",
    "repairs.date": "Date Reported",
    "repairs.add": "Add Repair Request",
    "repairs.edit": "Edit Repair",
    "repairs.delete": "Delete Repair",
    "language.en": "English",
    "language.th": "Thai",
    "theme.light": "Light",
    "theme.dark": "Dark",
    "roomer.text1": "Room Status",
    "roomer.text2": "Current room occupancy",
    "footer.rights": "All rights reserved",
    "welcome.title": "Welcome to Ban Phuttachad, Nakhon Pathom",
    "welcome.subtitle": "Modern living spaces for students",
    "welcome.login": "Login ",
    "welcome.explore": "Rooms Detils",
    "welcome.features": "Our Features",
    "welcome.location": "Prime Location",
    "welcome.security": "24h Security",
    "welcome.amenities": "Modern Amenities",
    "welcome.contact": "Contact Us",
    "profile.title": "Profile",
    "profile.manage": "Manage your personal information",
    "profile.firstName": "First Name",
    "profile.lastName": "Last Name",
    "profile.email": "Email",
    "profile.phone": "Phone Number",
    "profile.address": "Address",
    "profile.enterPhone": "Enter your phone number",
    "profile.enterAddress": "Enter your address",
    "profile.save": "Save Changes",
    "profile.saving": "Saving...",
    "profile.saveSuccess": "Profile saved successfully!",
    "profile.saveError": "Could not save profile",
    "profile.userNotFound": "User not found",
    "profile.genericError": "An error occurred while saving",
    "system.title": "System Settings",
    "system.description": "System configuration and maintenance (admin only)",
    "system.info": "System Information",
    "system.totalRooms": "Total Rooms",
    "system.occupiedRooms": "Occupied Rooms",
    "system.totalTenants": "Total Tenants",
    "system.pendingRepairs": "Pending Repairs",
    "system.config": "System Configuration",
    "system.waterRate": "Water Rate (THB/unit)",
    "system.electricityRate": "Electricity Rate (THB/unit)",
    "system.lateFee": "Late Payment Fee (%)",
    "system.depositRate": "Deposit Rate (times rent)",
    "system.save": "Save Settings",
    "system.saving": "Saving...",
    "system.maintenance": "System Maintenance",
    "system.backup": "Backup Data",
    "system.backuping": "Backing up...",
    "system.backupSuccess": "Backup completed!",
    "system.backupError": "Could not backup data",
    "system.clearCache": "Clear Cache",
    "system.clearCacheSuccess": "Cache cleared!",
    "system.clearCacheError": "Could not clear cache",
    "system.check": "System Check",
    "system.status": "System Status",
    "system.database": "Database",
    "system.connection": "Connection",
    "system.storage": "Storage",
    "system.normal": "Normal",
    "system.used": "Used 65%",
    "reports.title": "Reports",
    "reports.subtitle": "View and analyze dormitory data",
    "reports.export": "Export",
    "reports.options": "Report Options",
    "reports.optionsDesc": "Select the report type and time frame",
    "reports.type": "Report Type",
    "reports.period": "Time Period",
    "reports.period.month": "This Month",
    "reports.period.quarter": "This Quarter",
    "reports.period.year": "This Year",
    "reports.period.custom": "Custom Range",
    "reports.occupancy.title": "Occupancy Trends",
    "reports.occupancy.desc": "Monthly occupancy rates for the dormitory",
    "reports.occupancy.label": "Occupancy Rate",
    "reports.revenue.title": "Revenue Analysis",
    "reports.revenue.desc": "Monthly revenue data for the dormitory",
    "reports.revenue.label": "Revenue",
    "reports.rooms.title": "Room Type Distribution",
    "reports.rooms.desc":
      "Distribution of different room types in the dormitory",
    "reports.repairs.title": "Repair Request Analysis",
    "reports.repairs.desc":
      "Distribution of different types of repair requests",
    "reports.events.title": "Event Attendance",
    "reports.events.desc": "This report is not available yet",
    "reports.comingSoon": "Coming Soon",
    "reports.comingSoonDesc":
      "Event attendance analytics are currently being developed and will be available soon.",
    "reports.rooms.label": "Rooms",
    "reports.repairs.label": "Requests",
    "month.Jan": "Jan",
    "month.Feb": "Feb",
    "month.Mar": "Mar",
    "month.Apr": "Apr",
    "month.May": "May",
    "month.Jun": "Jun",
    "month.Jul": "Jul",
    "month.Aug": "Aug",
    "month.Sep": "Sep",
    "month.Oct": "Oct",
    "month.Nov": "Nov",
    "month.Dec": "Dec",
    "announcements.add": "Add Announcement",
    "announcements.createDescription":
      "Create a new announcement for residents.",
    "announcements.title": "Title",
    "announcements.titlePlaceholder": "Announcement Title",
    "announcements.content": "Content",
    "announcements.contentPlaceholder": "Announcement details...",
    "announcements.date": "Date",
    "announcements.markImportant": "Mark as Important",
    "announcements.calendar": "Calendar",
    "announcements.forDate": "Announcements for ",
    "announcements.today": "Today",
    "announcements.important": "Important",
    "announcements.edit": "Edit",
    "announcements.delete": "Delete",
    "announcements.noForDate": "No announcements for this date",
    "announcements.recent": "Recent Announcements",
    "announcements.noAvailable": "No announcements available",
    "announcements.added": "Announcement Added",
    "announcements.addedDesc": "The announcement has been successfully added.",
    "announcements.deleted": "Announcement Deleted",
    "announcements.deletedDesc":
      "The announcement has been successfully deleted.",
    "days.Sun": "Sun",
    "days.Mon": "Mon",
    "days.Tue": "Tue",
    "days.Wed": "Wed",
    "days.Thu": "Thu",
    "days.Fri": "Fri",
    "days.Sat": "Sat",
    "type.text": "type",
    "Actions.text": "Actions",
    "View.Details": "View Details",
    "Edit.text": "Edit",
    "Change.Status": "Change Status",
    "Set.as": "Set as",
    "Roomstatus.has": "Room status has been updated to",
    "repairs.actions" : "Actions",
    // Add more translations as needed
  },
  th: {
    "app.title": "บ้านพุทธชาติ",
    "nav.dashboard": "แดชบอร์ด",
    "nav.rooms": "ห้องพัก",
    "nav.tenants": "ผู้เช่า",
    "nav.staff": "พนักงาน",
    "nav.billing": "การเงิน",
    "nav.repairs": "แจ้งซ่อม",
    "nav.announcements": "ประกาศ",
    "nav.reports": "รายงาน",
    "nav.profile": "โปรไฟล์",
    "nav.settings": "ตั้งค่า",
    "auth.login": "เข้าสู่ระบบ",
    "auth.logout": "ออกจากระบบ",
    "auth.register": "ลงทะเบียน",
    "auth.email": "อีเมล",
    "auth.password": "รหัสผ่าน",
    "auth.confirmPassword": "ยืนยันรหัสผ่าน",
    "auth.role": "ตำแหน่ง",
    "auth.welcomeBack": "ยินดีต้อนรับกลับ",
    "auth.pleaseLogin": "กรุณาเข้าสู่ระบบเพื่อดำเนินการต่อ",
    "dashboard.welcome": "ยินดีต้อนรับสู่แดชบอร์ดของคุณ",
    "dashboard.summary": "นี่คือสรุปข้อมูลหอพักของคุณ",
    "dashboard.totalRooms": "จำนวนห้องทั้งหมด",
    "dashboard.occupiedRooms": "ห้องที่มีผู้เช่า",
    "dashboard.vacantRooms": "ห้องว่าง",
    "dashboard.pendingRepairs": "การซ่อมแซมที่รอดำเนินการ",
    "dashboard.monthlyRevenue": "รายได้ประจำเดือน",
    "dashboard.Description": "แนวโน้มรายได้ในช่วง 6 เดือนที่ผ่านมา",
    "rooms.management": "จัดการห้องพัก",
    "rooms.number": "หมายเลขห้อง",
    "rooms.type": "ประเภทห้อง",
    "rooms.status": "สถานะ",
    "rooms.rent": "ค่าเช่ารายเดือน",
    "rooms.size": "ขนาดห้อง",
    "rooms.add": "เพิ่มห้อง",
    "rooms.add_description": "เพิ่มห้องพักใหม่ภายในหอพัก",
    "Standard.Single": "ห้องเดี่ยวมาตรฐาน",
    "Standard.Double": "ห้องคู่มาตรฐาน",
    "satatus.occupied": "มีผู้เช่า",
    "satatus.vacant": "ห้องว่าง",
    "satatus.maintenance": "อยู่ระหว่างซ่อมแซม",
    "rooms.capacity": "ความจุ",
    "rooms.Floor": "ชั้น",
    "status.text": "สถานะห้อง",
    "rooms.edit": "แก้ไขห้อง",
    "rooms.delete": "ลบห้อง",
    "tenants.management": "จัดการผู้เช่า",
    "tenants.name": "ชื่อ",
    "tenants.room": "ห้อง",
    "tenants.contactInfo": "ข้อมูลติดต่อ",
    "tenants.leaseStart": "วันเริ่มสัญญา",
    "tenants.leaseEnd": "วันสิ้นสุดสัญญา",
    "tenants.add": "เพิ่มผู้เช่า",
    "tenants.edit": "แก้ไขข้อมูลผู้เช่า",
    "tenants.delete": "ลบผู้เช่า",
    "repairs.management": "จัดการการซ่อมแซม",
    "repairs.room": "ห้อง",
    "repairs.description": "รายละเอียด",
    "repairs.status": "สถานะ",
    "repairs.date": "วันที่แจ้ง",
    "repairs.add": "เพิ่มการแจ้งซ่อม",
    "repairs.edit": "แก้ไขการซ่อม",
    "repairs.delete": "ลบการซ่อม",
    "language.en": "อังกฤษ",
    "language.th": "ไทย",
    "theme.light": "สว่าง",
    "theme.dark": "มืด",
    "roomer.text1": "สถานะห้องพัก",
    "roomer.text2": "จำนวนผู้เข้าพักห้องปัจจุบัน",
    "footer.rights": "สงวนลิขสิทธิ์",
    "welcome.title": "ยินดีต้อนรับสู่หอพักบ้านพุทธชาติ นครปฐม",
    "welcome.subtitle": "พื้นที่พักอาศัยทันสมัยสำหรับนักศึกษา",
    "welcome.login": "เข้าสู่ระบบเพื่อเข้าถึงบัญชีของคุณ",
    "welcome.explore": "ดูห้องพักที่มี",
    "welcome.features": "สิ่งอำนวยความสะดวก",
    "welcome.location": "ทำเลดี",
    "welcome.security": "ระบบรักษาความปลอดภัย 24 ชั่วโมง",
    "welcome.amenities": "สิ่งอำนวยความสะดวกทันสมัย",
    "welcome.contact": "ติดต่อเรา",
    "profile.title": "โปรไฟล์ส่วนตัว",
    "profile.manage": "จัดการข้อมูลส่วนตัวของคุณ",
    "profile.firstName": "ชื่อ",
    "profile.lastName": "นามสกุล",
    "profile.email": "อีเมล",
    "profile.phone": "เบอร์โทรศัพท์",
    "profile.address": "ที่อยู่",
    "profile.enterPhone": "กรุณาใส่เบอร์โทรศัพท์",
    "profile.enterAddress": "กรุณาใส่ที่อยู่",
    "profile.save": "บันทึกการเปลี่ยนแปลง",
    "profile.saving": "กำลังบันทึก...",
    "profile.saveSuccess": "บันทึกโปรไฟล์สำเร็จ!",
    "profile.saveError": "ไม่สามารถบันทึกโปรไฟล์ได้",
    "profile.userNotFound": "ไม่พบข้อมูลผู้ใช้",
    "profile.genericError": "เกิดข้อผิดพลาดในการบันทึกข้อมูล",
    "system.title": "ตั้งค่าระบบ",
    "system.description": "การตั้งค่าระบบและการบำรุงรักษา (เฉพาะผู้ดูแลระบบ)",
    "system.info": "ข้อมูลระบบ",
    "system.totalRooms": "ห้องทั้งหมด",
    "system.occupiedRooms": "ห้องที่เช่าแล้ว",
    "system.totalTenants": "ผู้เช่าทั้งหมด",
    "system.pendingRepairs": "งานซ่อมรอดำเนินการ",
    "system.config": "การตั้งค่าระบบ",
    "system.waterRate": "อัตราค่าน้ำ (บาท/หน่วย)",
    "system.electricityRate": "อัตราค่าไฟ (บาท/หน่วย)",
    "system.lateFee": "ค่าปรับชำระล่าช้า (%)",
    "system.depositRate": "อัตราเงินมัดจำ (เท่าของค่าเช่า)",
    "system.save": "บันทึกการตั้งค่า",
    "system.saving": "กำลังบันทึก...",
    "system.maintenance": "การบำรุงรักษาระบบ",
    "system.backup": "สำรองข้อมูล",
    "system.backuping": "กำลังสำรอง...",
    "system.backupSuccess": "สำรองข้อมูลเสร็จสิ้น!",
    "system.backupError": "ไม่สามารถสำรองข้อมูลได้",
    "system.clearCache": "ล้าง Cache",
    "system.clearCacheSuccess": "ล้าง Cache เสร็จสิ้น!",
    "system.clearCacheError": "ไม่สามารถล้าง Cache ได้",
    "system.check": "ตรวจสอบระบบ",
    "system.status": "สถานะระบบ",
    "system.database": "ฐานข้อมูล",
    "system.connection": "การเชื่อมต่อ",
    "system.storage": "พื้นที่จัดเก็บข้อมูล",
    "system.normal": "ปกติ",
    "system.used": "ใช้ไป 65%",
    "reports.title": "รายงาน",
    "reports.subtitle": "ดูและวิเคราะห์ข้อมูลหอพัก",
    "reports.export": "ส่งออก",
    "reports.options": "ตัวเลือกการรายงาน",
    "reports.optionsDesc": "เลือกประเภทและช่วงเวลาของรายงาน",
    "reports.type": "ประเภทของรายงาน",
    "reports.period": "ช่วงเวลา",
    "reports.period.month": "เดือนนี้",
    "reports.period.quarter": "ไตรมาสนี้",
    "reports.period.year": "ปีนี้",
    "reports.period.custom": "กำหนดเอง",
    "reports.occupancy.title": "แนวโน้มการเข้าพัก",
    "reports.occupancy.desc": "อัตราการเข้าพักรายเดือนของหอพัก",
    "reports.occupancy.label": "อัตราการเข้าพัก",
    "reports.revenue.title": "วิเคราะห์รายได้",
    "reports.revenue.desc": "ข้อมูลรายได้รายเดือนของหอพัก",
    "reports.revenue.label": "รายได้",
    "reports.rooms.title": "สัดส่วนประเภทห้องพัก",
    "reports.rooms.desc": "สัดส่วนประเภทห้องพักแต่ละประเภทในหอพัก",
    "reports.repairs.title": "วิเคราะห์การแจ้งซ่อม",
    "reports.repairs.desc": "สัดส่วนประเภทการแจ้งซ่อมแต่ละประเภท",
    "reports.events.title": "การเข้าร่วมกิจกรรม",
    "reports.events.desc": "รายงานนี้ยังไม่พร้อมใช้งาน",
    "reports.comingSoon": "เร็ว ๆ นี้",
    "reports.comingSoonDesc":
    "การวิเคราะห์การเข้าร่วมกิจกรรมกำลังพัฒนาและจะพร้อมใช้งานเร็ว ๆ นี้",
    "reports.rooms.label": "ห้อง",
    "reports.repairs.label": "รายการแจ้งซ่อม",
    "month.Jan": "ม.ค.",
    "month.Feb": "ก.พ.",
    "month.Mar": "มี.ค.",
    "month.Apr": "เม.ย.",
    "month.May": "พ.ค.",
    "month.Jun": "มิ.ย.",
    "month.Jul": "ก.ค.",
    "month.Aug": "ส.ค.",
    "month.Sep": "ก.ย.",
    "month.Oct": "ต.ค.",
    "month.Nov": "พ.ย.",
    "month.Dec": "ธ.ค.",
    "announcements.add": "เพิ่มประกาศ",
    "announcements.createDescription": "สร้างประกาศใหม่สำหรับผู้อยู่อาศัย",
    "announcements.title": "หัวข้อ",
    "announcements.titlePlaceholder": "หัวข้อประกาศ",
    "announcements.content": "เนื้อหา",
    "announcements.contentPlaceholder": "รายละเอียดประกาศ...",
    "announcements.date": "วันที่",
    "announcements.markImportant": "ทำเครื่องหมายว่าสำคัญ",
    "announcements.calendar": "ปฏิทิน",
    "announcements.forDate": "ประกาศวันที่ ",
    "announcements.today": "วันนี้",
    "announcements.important": "สำคัญ",
    "announcements.edit": "แก้ไข",
    "announcements.delete": "ลบ",
    "announcements.noForDate": "ไม่มีประกาศสำหรับวันนี้",
    "announcements.recent": "ประกาศล่าสุด",
    "announcements.noAvailable": "ไม่มีประกาศ",
    "announcements.added": "เพิ่มประกาศแล้ว",
    "announcements.addedDesc": "เพิ่มประกาศสำเร็จ",
    "announcements.deleted": "ลบประกาศแล้ว",
    "announcements.deletedDesc": "ลบประกาศสำเร็จ",
    "days.Sun": "อา",
    "days.Mon": "จ",
    "days.Tue": "อ",
    "days.Wed": "พ",
    "days.Thu": "พฤ",
    "days.Fri": "ศ",
    "days.Sat": "ส",
    "type.text": "ประเภท",
    "Actions.text": "การดำเนินการ",
    "View.Details": "ดูรายละเอียด",
    "Edit.text": "แก้ไข",
    "Change.Status": "เปลี่ยนสถานะ",
    "Set.as": "ตั้งเป็น",
    "Roomstatus.has": "สถานะห้องพักได้ถูกอัปเดตเป็น",
    "repairs.actions" : "แอ็กชัน",
    // Add more translations as needed
  },
};

export function LanguageProvider({
  children,
  defaultLanguage = "en",
}: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>(
    () => (localStorage.getItem("language") as Language) || defaultLanguage
  );

  useEffect(() => {
    document.documentElement.setAttribute("lang", language);
    localStorage.setItem("language", language);
  }, [language]);

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const value = {
    language,
    setLanguage: (language: Language) => {
      setLanguage(language);
    },
    t,
  };

  return (
    <LanguageProviderContext.Provider value={value}>
      {children}
    </LanguageProviderContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageProviderContext);

  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }

  return context;
};
