
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnsotnlftoumjwjlvzus.supabase.co";
// The service role key should be kept secret and not exposed in client-side code.
const SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uc290bmxmdG91bWp3amx2enVzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0ODAxMjg1NiwiZXhwIjoyMDYzNTg4ODU2fQ.gsi0MzKR0s2kIsFFEspAuz5G75soMI8hQmcToYiiIOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supersupabase = createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
